### ISSUE TITLE
Publish current version to pub

### ISSUE THREAD

**Issue by martflu** [conradkleinespel/levenshtein-dart#2]
We tried to use your library but got:
```
Package unittest has no versions that match 0.9.3 derived from:
- levenshtein 1.0.2 depends on version 0.9.3
```
Could you please publish the current version to pub.

**Comment by conradkleinespel** [comment]
Hello @martflu ,

I can't. I have lost access to my Google account and cannot recover it. Sorry.

Best regards,
Conrad
